<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-13 14:14
=======
# Generated by Django 5.2.6 on 2025-09-14 15:09
>>>>>>> 81c30c68e201b27ff25fd8df7db601abd3a4824a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_contact', models.CharField(max_length=20)),
=======
                ('employee_id', models.CharField(max_length=30)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('employee_contact', models.CharField(max_length=15)),
                ('hire_date', models.DateField(auto_now_add=True)),
>>>>>>> 81c30c68e201b27ff25fd8df7db601abd3a4824a
            ],
        ),
    ]
