# Generated by Django 5.2.6 on 2025-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_hire_date_remove_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
