# Generated by Django 5.2.6 on 2025-09-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
