# Generated by Django 5.2.6 on 2025-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
